source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pre_install do |installer|
# workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
def installer.verify_no_static_framework_transitive_dependencies; end
end

target 'PodsDemo' do
    #pod 'Charts/Realm', '~> 3.0.1'
    pod 'SwiftCharts', '~> 0.5'
   # pod 'BaiduMapKit' 网络不好，下载失败
    pod 'LocationLib', :path => "../LocationLib"
end
